apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: brim-sol-net-change-service
  name: brim-sol-net-change-service
  namespace: bsl-ms
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: brim-sol-net-change-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: brim-sol-net-change-service
    spec:
      containers:
        - image: gcr.io/gcp-cptmazatlan-nprd-77193/brim-sol-net-change-service:v1
          imagePullPolicy: IfNotPresent
          name: operate
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: brim-sol-net-change-service
  name: brim-sol-net-change-service
  namespace: bsl-ms
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8085
      protocol: TCP
      targetPort: 8085
  publishNotReadyAddresses: true
  selector:
    app: brim-sol-net-change-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: brim-sol-net-change-service
spec:
  hosts:
    - "*"
  gateways:
    - istio-gateway.istio-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /api/bsl/net-change        
      rewrite:
        uri: "/"
      route:
        - destination:
            host: brim-sol-net-change-service.bsl-ms.svc.cluster.local
            port:
              number: 8085